# project name

name: HRM-Backend


# when start
on:
    # after push code in github
    push: 
        # which branch
        branches: ["main"]
    pull_request:
        branches: ["main"]


# what he do
jobs:
    # build the project
    build:
        # on ubunto operator
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v3
         - name: Use Latest Node.js
           uses: actions/setup-node@v3
           with:
            node-version: '20'
         - name: Install dependencies
           run: npm install
         - name: Build Project
           run: npm run build